// TODO: Store this in the database and fetch it from there

export const additionalInstruction: string[] = [
  'USE ONLY HSK 1-LEVEL VOCABULARY, focusing on words and phrases that the learner is likely familiar with. Avoid complicated words or sentence structures. If the learner struggles, offer simpler words or phrases to help them understand.',
  'USE HSK 2-LEVEL VOCABULARY, focusing on words and phrases that build upon HSK 1. Use slightly longer and more detailed sentences compared to HSK 1, but still avoid complex grammar structures. Introduce common question words, adjectives, and phrases related to daily life, hobbies, and basic activities. If the learner struggles, offer explanations using HSK 1 vocabulary or break sentences into smaller parts for better understanding.',
  'USE HSK 3-LEVEL VOCABULARY, focusing on practical scenarios such as shopping, travel, health, and social interactions. Use compound sentences with common conjunctions (e.g., 因为, 所以, 但是), and introduce more descriptive adjectives and verbs. Aim for sentences that require understanding of slightly abstract ideas, like expressing preferences, plans, and experiences. If the learner struggles, simplify sentences by removing conjunctions or switching to HSK 2-level vocabulary.',
  'USE HSK 4-LEVEL VOCABULARY, incorporating words and phrases that reflect more complex topics like work, emotions, and opinions. Use a mix of compound and complex sentences with conjunctions like 虽然...但是, 如果...就. Introduce idiomatic expressions and slightly formal phrases where appropriate. Questions should challenge learners to articulate ideas, not just facts. If the learner struggles, provide definitions or examples using HSK 3 vocabulary.',
  'USE HSK 5-LEVEL VOCABULARY, focusing on more abstract and formal topics such as culture, education, and societal issues. Use varied sentence structures, including complex sentences with relative clauses (的, 地, 得) and transitional phrases (此外, 然而, 因此). Encourage learners to form detailed answers, express opinions, and analyze situations. Introduce idiomatic and context-specific expressions.',
];
